### ISSUE TITLE
Not Serving Anything

### ISSUE THREAD

**Issue by stalinkay** [steve-taylor/node-download-server#1]
@steve-taylor Hi, I like the idea of your download server. I'm planning to use it to serve files that I don't want anyone to be able to access freely. However, I have run it with the following command `node . --apiKey secret123 --publicDir ./public --privateDir ./private` to no avail. None of the end points are working. Kindly test and fix or point me in the right direction.

**Browser**
```
Cannot GET /private/
```

**Terminal Out**
```
Starting the download server...

Download server running.
 - Serving public files in ./public from http://localhost:3000/public
 - Serving private files in ./private from http://localhost:3000/private
 - To create a link, POST ${{ "filename": "/path/to/file" } (with the header apiKey: secret123 to http://localhost:3000/api/1/createLink
 - Links to private files expire 300 seconds after they are created
```

**Comment by steve-taylor** [comment]
Did you try POSTing something to http://localhost:3000/api/1/createLink first?

**Comment by stalinkay** [comment]
@steve-taylor, thanks for your prompt reply. I thought I could simply point it to a folder and it will sort things out. Thanks I will do try that. Will close this for now, pending any further problems.
